apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-a-2329258
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-a-2329258
  template:
    metadata:
      labels:
        app: devops-a-2329258
    spec:
      containers:
        - name: devops-a-2329258
          image: devops-a-2329258:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
